events {}

http {
  upstream catalog_service {
    server catalog-service:3001;
  }

  upstream order_service {
    server order-service:3002;
  }

  upstream inventory_service {
    server inventory-service:3004;
  }

  upstream notification_service {
    server notification-service:3003;
  }

  server {
    listen 8080;

    location = /api/orders {
      proxy_pass http://order_service/api/orders;
    }

    location /api/catalog/ {
      proxy_pass http://catalog_service/api/;
    }

    location /api/orders/ {
      proxy_pass http://order_service/api/orders/;
    }

    location /api/inventory/ {
      proxy_pass http://inventory_service;
    }

    location = /api/inventory {
      proxy_pass http://inventory_service/api/inventory;
    }

    location /api/admin/ {
      proxy_pass http://notification_service/admin/;
    }
  }
}
